name: Test and Confirm GitHub Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: Install Latest Stable Terraform
      run: |
        curl -sL https://releases.hashicorp.com/terraform/index.json | jq -r '.versions[].builds[].url' | grep 'linux.*amd64' | grep -v 'beta' | sort -V | tail -n1 | wget -i -
        unzip -o terraform_*_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform -version

    - name: Terraform Init
      run: |
        cd "${{ github.workspace }}/terraform"
        terraform init

    - name: Terraform Plan
      run: |
        cd "${{ github.workspace }}/terraform"
        terraform plan -out=tfplan 2>&1 | tee "$RUNNER_TEMP/${{ github.run_id }}_terraform_output_file.txt"

    - name: Test and Confirm GitHub Action
      uses: ./ # Or use the repository URL if testing from another repository
      with:
        output_file: "$RUNNER_TEMP/${{ github.run_id }}_terraform_output_file.txt"